### What is numpy?

#### ndarray is the base/core object
- scientific computing package
- provides n-dimensional array objects and various mathematical operations
- *Numpy Arrays has fixed size at creation*
- *Homogenous datatype*
- *written in C*

### importing numpy package

In [2]:
import numpy as np

### creating numpy arrays

In [3]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [24]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


### Attributes

*dtype*,
*ndim*

In [5]:
# dtype

print(b.dtype)

int32


In [8]:
c = np.array([1,2,3],dtype="float32")

print(c)
print(c.dtype)

[1. 2. 3.]
float32


### shape

In [10]:
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


### ndim

In [13]:
# ndim gives the dimension of the numpy array
print(b.ndim)

2


In [14]:
print(a)
print(a.ndim)

[1 2 3]
1


### arange

In [18]:
d = np.arange(1,11,2)
print(d)

[1 3 5 7 9]


In [16]:
np.arange(4)

array([0, 1, 2, 3])

### reshape

In [20]:
f = np.arange(16).reshape(2,2,2,2)

In [21]:
print(f)
print(f.shape)
print(f.ndim)
print(f.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
(2, 2, 2, 2)
4
int32


### size, itemsize, nbytes
*These are also other attributes*

In [23]:
# number of elements
print(f.size)

16
