### What is numpy?

#### ndarray is the base/core object
- scientific computing package
- provides n-dimensional array objects and various mathematical operations
- *Numpy Arrays has fixed size at creation*
- *Homogenous datatype*
- *written in C*

### importing numpy package

In [1]:
import numpy as np

### creating numpy arrays

In [2]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


### Attributes

*dtype*,
*ndim*

In [5]:
# dtype

print(b.dtype)

int32


In [6]:
c = np.array([1,2,3],dtype="float32")

print(c)
print(c.dtype)

[1. 2. 3.]
float32


### shape

In [7]:
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


### ndim

In [8]:
# ndim gives the dimension of the numpy array
print(b.ndim)

2


In [9]:
print(a)
print(a.ndim)

[1 2 3]
1


### arange

In [10]:
d = np.arange(1,11,2)
print(d)

[1 3 5 7 9]


In [11]:
np.arange(4)

array([0, 1, 2, 3])

### reshape

In [12]:
f = np.arange(16).reshape(2,2,2,2)

In [13]:
print(f)
print(f.shape)
print(f.ndim)
print(f.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
(2, 2, 2, 2)
4
int32


### size, itemsize, nbytes
*These are also other attributes*

In [14]:
# number of elements
print(f.size)

16


In [15]:
print(f.dtype) # type of the values stored 
print(f.itemsize) # size of each element in bytes
print(f.nbytes) # total memory occupies

int32
4
64


In [16]:
f = np.arange(16.0).reshape(2,2,2,2)

In [17]:
print(f.dtype) # type of the values stored 
print(f.itemsize) # size of each element in bytes
print(f.nbytes) # total memory occupies

float64
8
128


### ones,zeros

In [18]:
o = np.ones((3,4),dtype=np.int32)
print(o)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### random

In [19]:
np.random.seed(42)
np.random.rand(4,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [20]:
np.random.randint(5,78,size=5)

array([63, 46, 64, 19, 66])

In [21]:
np.random.seed(42)
np.random.random((1,2))

array([[0.37454012, 0.95071431]])

In [22]:
np.random.uniform(5,6,size =(4,3))

array([[5.73199394, 5.59865848, 5.15601864],
       [5.15599452, 5.05808361, 5.86617615],
       [5.60111501, 5.70807258, 5.02058449],
       [5.96990985, 5.83244264, 5.21233911]])

In [23]:
rng = np.random.default_rng(seed=42)

rng.random(4)


array([0.77395605, 0.43887844, 0.85859792, 0.69736803])

### linspace

In [24]:
np.linspace(10,5,17,dtype=int)

array([10,  9,  9,  9,  8,  8,  8,  7,  7,  7,  6,  6,  6,  5,  5,  5,  5])

### identity

In [25]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Changing datatype

In [26]:
f.dtype

dtype('float64')

In [27]:
f

array([[[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]]],


       [[[ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.]]]])

In [28]:
f.astype(np.int32)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### array operation

In [29]:
a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(3,4)


In [30]:
print(a)
print(a**2)
print(a*3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


In [31]:
print(a==5)

[[False False False]
 [False False  True]
 [False False False]
 [False False False]]


### dot product

In [32]:
print(np.dot(a,b))

[[ 56  59  62  65]
 [200 212 224 236]
 [344 365 386 407]
 [488 518 548 578]]


In [33]:
a@b

array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

In [34]:
print(a*b.reshape(4,3))

[[  0  13  28]
 [ 45  64  85]
 [108 133 160]
 [189 220 253]]


In [35]:
print(a**b.reshape(4,3))

[[          0           1       16384]
 [   14348907           0 -1564725563]
 [ 1159987200   442181591           0]
 [ 1914644777 -1304428544  -122979837]]


In [36]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
#np.max/min/sum/prod
np.sum(a,axis=1) # 1=row

array([ 3, 12, 21, 30])

In [38]:
np.prod(a,axis=0)

array([  0, 280, 880])

In [39]:
#np.sin
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021]])

In [40]:
#mean,median,std,var

np.mean(a,axis=1)

array([ 1.,  4.,  7., 10.])

In [41]:
c = np.random.random((3,4))*100
print(c)

[[18.18249672 18.34045099 30.4242243  52.47564316]
 [43.19450186 29.12291402 61.18528947 13.94938607]
 [29.21446485 36.63618433 45.60699842 78.51759614]]


In [42]:
np.round(c)

array([[18., 18., 30., 52.],
       [43., 29., 61., 14.],
       [29., 37., 46., 79.]])

In [43]:
#np.floor
np.ceil(c)

array([[19., 19., 31., 53.],
       [44., 30., 62., 14.],
       [30., 37., 46., 79.]])

In [44]:
#exp,log
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

### traversal

In [45]:
for i in a:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [46]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### reshape

In [47]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [48]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [49]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### stacking, splitting

In [50]:
a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(4,3)

In [51]:
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [57]:
np.hstack((a,b,a)) # rows must be same

array([[ 0,  1,  2, 12, 13, 14,  0,  1,  2],
       [ 3,  4,  5, 15, 16, 17,  3,  4,  5],
       [ 6,  7,  8, 18, 19, 20,  6,  7,  8],
       [ 9, 10, 11, 21, 22, 23,  9, 10, 11]])

In [53]:
c = np.vstack((a,b)) #columns must be same
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [54]:
np.hsplit(c,3)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18],
        [21]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16],
        [19],
        [22]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17],
        [20],
        [23]])]

In [55]:
np.vsplit(c,2)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])]

In [56]:
np.vsplit(c,4)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]