In [18]:
import numpy as np

In [19]:
a = np.random.randint(1,20,5)

In [20]:
np.sort(a)

array([ 4, 10, 11, 11, 16])

In [21]:
np.sort(a)[::-1]

array([16, 11, 11, 10,  4])

In [22]:
b = np.random.randint(1,100,size=(4,5))
print(b)

[[57 51 67 87 66]
 [69 82 56 14 87]
 [ 9 99  7 10 12]
 [81 40 81 20 76]]


*default sorted rowwise*

In [23]:
# np.sort(b)
np.sort(b,axis=1)

array([[51, 57, 66, 67, 87],
       [14, 56, 69, 82, 87],
       [ 7,  9, 10, 12, 99],
       [20, 40, 76, 81, 81]])

In [24]:
np.sort(b,axis=0)

array([[ 9, 40,  7, 10, 12],
       [57, 51, 56, 14, 66],
       [69, 82, 67, 20, 76],
       [81, 99, 81, 87, 87]])

### append,concatenate

In [25]:
a.dtype

dtype('int32')

In [26]:
a = np.append(a,23.0)

In [27]:
a.dtype

dtype('float64')

In [28]:
b

array([[57, 51, 67, 87, 66],
       [69, 82, 56, 14, 87],
       [ 9, 99,  7, 10, 12],
       [81, 40, 81, 20, 76]])

In [33]:
np.append(b,np.random.rand(b.shape[0],1),axis=1)

array([[57.        , 51.        , 67.        , 87.        , 66.        ,
         0.90330778],
       [69.        , 82.        , 56.        , 14.        , 87.        ,
         0.51600953],
       [ 9.        , 99.        ,  7.        , 10.        , 12.        ,
         0.11246608],
       [81.        , 40.        , 81.        , 20.        , 76.        ,
         0.67113287]])

In [35]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [37]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### unique,expand_dims,where,argmax,cumsum,cumprod

In [42]:
dup = np.array((77,11,22,22,33,11,22))

In [43]:
np.unique(dup)

array([11, 22, 33, 77])

In [44]:
dup.shape

(7,)

In [48]:
np.expand_dims(dup,axis=0).shape

(1, 7)

In [51]:
np.expand_dims(dup,axis=1).shape

(7, 1)

In [52]:
np.where(dup > 20)

(array([0, 2, 3, 4, 6], dtype=int64),)

In [55]:
#replace values > 20 with 99
np.where(dup>20,99,dup)

array([99, 11, 99, 99, 99, 11, 99])

In [56]:
print(dup)
np.argmax(dup)

[77 11 22 22 33 11 22]


0

In [57]:
np.argmin(dup)

1

In [58]:
b

array([[57, 51, 67, 87, 66],
       [69, 82, 56, 14, 87],
       [ 9, 99,  7, 10, 12],
       [81, 40, 81, 20, 76]])

In [62]:
np.argmax(b)

11

In [61]:
np.argmax(b,axis=0)

array([3, 2, 3, 0, 1], dtype=int64)

In [63]:
np.cumsum(b)

array([  57,  108,  175,  262,  328,  397,  479,  535,  549,  636,  645,
        744,  751,  761,  773,  854,  894,  975,  995, 1071])

### percentile

In [64]:
a

array([16., 10., 11., 11.,  4., 23.])

In [65]:
np.percentile(a,50)

11.0

In [66]:
np.median(a)

11.0

In [67]:
a = np.random.randint(1,50,size=20)

### histogram

In [69]:
a

array([31,  3, 32,  7, 10,  5, 28, 46, 41,  4,  2, 40, 29, 30, 45, 36, 18,
       12, 12, 34])

In [68]:
np.histogram(a,bins=[0,10,20,30,40,50])

(array([5, 4, 2, 5, 4], dtype=int64), array([ 0, 10, 20, 30, 40, 50]))

### corrcoef

In [71]:
s = [1,2,3,4]
y = [1,4,9,16]

np.corrcoef(s,y)

array([[1.        , 0.98437404],
       [0.98437404, 1.        ]])

### isin

In [72]:
b = np.array((10,20))

np.isin(a,b)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

### flip

In [73]:
a

array([31,  3, 32,  7, 10,  5, 28, 46, 41,  4,  2, 40, 29, 30, 45, 36, 18,
       12, 12, 34])

In [74]:
np.flip(a)

array([34, 12, 12, 18, 36, 45, 30, 29, 40,  2,  4, 41, 46, 28,  5, 10,  7,
       32,  3, 31])

In [75]:
b = np.random.randint(1,100,size=(4,5))

In [76]:
b

array([[34, 37, 96, 95, 14],
       [75, 71, 68, 44, 83],
       [44, 95, 25, 88, 97],
       [68, 27, 90, 38, 31]])

### flip

In [77]:
np.flip(b)

array([[31, 38, 90, 27, 68],
       [97, 88, 25, 95, 44],
       [83, 44, 68, 71, 75],
       [14, 95, 96, 37, 34]])

In [79]:
a = np.arange(5)
np.put(a, [0, 2,3], [-41, -55,8148])
a

array([ -41,    1,  -55, 8148,    4])

In [80]:
a

array([ -41,    1,  -55, 8148,    4])

### delete

In [81]:
np.delete(a,[0,2])

array([   1, 8148,    4])

In [82]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
np.intersect1d(m,n)

array([3, 4, 5])

In [88]:
np.setdiff1d(n,m)

array([6, 7])

In [89]:
np.setdiff1d(m,n)

array([1, 2])

In [86]:
a = np.random.randint(1,50,20)
a

array([32, 41, 47, 35, 48, 25,  9, 14, 44,  4, 40, 25, 48, 43, 28, 32, 33,
       17, 37, 39])

In [87]:
np.clip(a,a_min=25,a_max=30)

array([30, 30, 30, 30, 30, 25, 25, 25, 30, 25, 30, 25, 30, 30, 28, 30, 30,
       25, 30, 30])

In [90]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
a = np.array([0,0,3,4,5,0,0,])
np.count_nonzero(a)

3

In [95]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [96]:
np.copyto(arr1,arr2)

In [97]:
arr1

array([4, 5, 6])

In [98]:
arr2

array([4, 5, 6])

In [99]:
np.repeat(567,6)

array([567, 567, 567, 567, 567, 567])

In [104]:
a = np.array(([1,2],[3,4]))

In [107]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [108]:
np.tile(a,3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [109]:
a = np.array([1.0, 2.0, 3.00000001])
b = np.array([1.0, 2.0, 3.0])

result = np.allclose(a, b)

In [110]:
result

True

In [111]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

result = np.array_equal(a, b)
print(result)  # Output: True


True


In [112]:
a==b

array([ True,  True,  True])

In [118]:
a = np.random.randint(1,50,(2,2,3))
a

array([[[ 7,  5, 22],
        [12, 43, 49]],

       [[24, 40, 40],
        [11, 28,  8]]])

In [121]:
np.swapaxes(a,0,2)

array([[[ 7, 24],
        [12, 11]],

       [[ 5, 40],
        [43, 28]],

       [[22, 40],
        [49,  8]]])

In [122]:
np.swapaxes(a,1,2)

array([[[ 7, 12],
        [ 5, 43],
        [22, 49]],

       [[24, 11],
        [40, 28],
        [40,  8]]])