### Slicing and Indexing of numpy arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [3]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(a2[2,0])
print(a2[2][0])

8
8


In [5]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
print(a3[1,1,1])
print(a3[1][1][1])

7
7


In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
print(a2[0:2,1::2])

[[1 3]
 [5 7]]


In [9]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
print(a3[1,1:,1:])

[[7]]


In [12]:
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [13]:
a[1,2]

8

In [19]:
#fancy indexing
a[[2],[1,5,4]]

array([13, 17, 16])

In [15]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [16]:
a[(a>10)&(a%2==0)]

array([12, 14, 16, 18, 20, 22])

In [18]:
a[~(a%2==0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

## Broadcasting

In [22]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3) # converted into (2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


`a = np.arange(12).reshape(3,4) ;`

`b = np.arange(3) # (1,3) => (3,3) => not matching`

`# So error`

In [23]:
a = np.arange(12).reshape(4,3)
b = np.arange(3) # (1,3) => (4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [24]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [25]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 